# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/imprenta_pereda
spring.datasource.username=postgres
spring.datasource.password=janira

# Mostrar consultas SQL
spring.jpa.show-sql=true

# Auto creación y actualización de tablas
spring.jpa.hibernate.ddl-auto=update

# Dialecto PostgreSQL para Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto del servidor
server.port=8081

# Configuración de CORS
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

